### ISSUE TITLE
How to use it in combination with console commands

### ISSUE THREAD

**Issue by elect86** [aaimio/set-persistent-value#2]
Hi,

first of all, nice project!

However I'm trying to find a way to set as a persistent value the lines number of a text file 

Code is [here](https://github.com/elect86/panama-foreign/blob/foreign-jextract/.github/workflows/submit.yml#L375):
```
      - name: Check that all tests executed successfully
                if: always()
                run: >
                  if ! grep --include=test-summary.txt -lqr build/*/test-results -e "TEST SUCCESS" ; then
                    cat build/*/test-results/*/text/newfailures.txt ;
                    // save persistent output of `wc -l < build/*/test-results/*/text/newfailures.txt`
                    exit 1 ;
```

But I have no idea how to connect it with the example syntax displayed on your [readme](https://github.com/aaimio/set-persistent-value#set-a-persistent-value)

Could you help me?

**Comment by aaimio** [comment]
Hey @elect86,

Apologies for my slow reply!

You could try the following:

- Set `wc -l < build/*/test-results/*/text/newfailures.txt` as an output to the `check_tests_executed` step
- Add a conditional `set-persistent-value` step after it.

Something like below:

```yml
- name: Check that all tests executed successfully
  id: check_tests_executed
  if: always()
  run: >
    if ! grep --include=test-summary.txt -lqr build/*/test-results -e "TEST SUCCESS" ; then
      cat build/*/test-results/*/text/newfailures.txt ;
      NUM_LINES=$(wc -l < build/*/test-results/*/text/newfailures.txt)
      echo "::set-output name=NUM_LINES::$NUM_LINES"
      exit 1 ;
    fi
- name: Set a persistent value
  id: set_persistent_value
  if: -z ${{ steps.check_tests_executed.outputs.NUM_LINES }}
  uses: aaimio/set-persistent-value@v1
  with:
    key: foo
    value: ${{ steps.check_tests_executed.outputs.NUM_LINES }}
    access_token: ${{ secrets.PERSISTENT_VALUE_ACCESS_TOKEN }}
```

I didn't test the above but with some testing it might do the job.

Let me know if it did or else we can look into other solutions.
